export const projects: GenType.CardImage[] = [
  {
    id: "fsd-glt",
    name: "GameLingo Tools",
    desc: {
      id: "Situs yang saya buat seorang diri. Awalnya, situs ini akan digunakan untuk membuat sebuah situs tentang Game, mulai dari blog, tools, dsb. Untuk sekarang masih terhenti dikarenakan ada kesibukan lain. Suatu saat akan dilanjutkan",
      en: "This site was made by my self. Firstly, this will be used for making a site about game, from blog, tools, etc. For now, this is deprecated cause there some job. One day, this will be continued",
    },
    imageSrc: "/images/Projects/fsd-glt.webp",
    imageAlt: "GameLingo Tools",
    imageCapt: "GameLingo Tools",
    group: [
      "Next Js",
      "Supabase",
      "Mongo DB",
      "Next Auth",
      "Cloudinary",
      "Next Intl",
    ],
    ctaText: "Lihat Situs",
    ctaLink: "https://gamelingo-tools.vercel.app/",
    repoText: "Source Code",
    repoLink: "https://github.com/aqil2514/gamelingo-tools",
  },
  {
    id: "fsd-moneyku",
    name: "Moneyku",
    desc: {
      id: "Situs yang saya buat seorang diri. Situs ini akan saya fokuskan untuk pencatatan keuangan dan akan ada beberapa fitur seperti budgeting, simulasi finansial, dsb.",
      en: "This site was made by my self. This site is focused on money management and there will be few features like as budgeting, financial simulation, etc",
    },
    imageSrc: "/images/Projects/fsd-moneyku.png",
    imageAlt: "Moneyku",
    imageCapt: "Moneyku",
    group: [
      "Remix Js",
      "Supabase",
      "Remix Auth",
      "Shadcn",
      "Express",
      "Typescript",
      "Tailwind",
      "SASS"
    ],
    ctaText: "Lihat Situs",
    ctaLink: "https://pengelolaan-keuangan.vercel.app/",
    repoText: "Source Code",
    repoLink: "https://github.com/aqil2514/pengelolaan-keuangan",
  },
];
